https://www.digitalocean.com/community/tutorials/python-scikit-learn-tutorial

In [1]:
import sklearn

In [2]:
from sklearn import datasets
# Load data
iris = datasets.load_iris()
# print shapre of data to coinfirm data is loaded
print(iris.data.shape)  

(150, 4)


scikit learn svm

In [3]:
from sklearn import svm
from sklearn import datasets
# Load dataset
iris = datasets.load_iris()
clf = svm.LinearSVC()
# learn from the data
clf.fit(iris.data, iris.target)
# predict for unseen data
clf.predict([[5.0, 3.0, 1.0, 0.25]])
# Parameters of model can be changed by using the attributes ending with an underscore
print(clf.coef_)

[[ 0.18344977  0.4549369  -0.81495365 -0.43357339]
 [ 0.05524625 -0.9008946   0.40923385 -0.9606271 ]
 [-0.85048831 -0.98657611  1.38090768  1.86511359]]


In [4]:
# import the model

from sklearn import linear_model
reg = linear_model.LinearRegression()
# use it to fit a data
reg.fit([[0, 0], [1, 1], [2, 2]], [0, 1, 2])
# lets look inth the fitted data
print(reg.coef_)

[0.5 0.5]


k-Nearest neighbour classifier

In [5]:
from sklearn import datasets# Load dataset
iris = datasets.load_iris()
# Create and fit a nearest-neighbor Classifier
from sklearn import neighbors
knn = neighbors.KNeighborsClassifier()
knn.fit(iris.data, iris.target)
# Predict and print the result
result=knn.predict([[0.1, 0.2, 0.3, 0.4]])
print(result)

[0]


K-means clustering

In [ ]:
from sklearn import cluster, datasets
# load data
iris = datasets.load_iris()
# create clusters for k=3
k=3
k_means = cluster.KMeans(k)
# fit the data
k_means.fit(iris.data)
# priunt results
print( k_means.labels_[::10]) # Prints the predicted cluster labels for every 10th sample
print( iris.target[::10])

[0 0 0 0 0 1 2 2 2 2 1 1 1 1 1]
[0 0 0 0 0 1 1 1 1 1 2 2 2 2 2]


Handling Large Datasets in Scikit-learn
Scikit-learn is a powerful library for machine learning, but it’s optimized for small to medium-sized datasets. When working with large datasets, you need to handle them efficiently. Here are some strategies:

* Use partial_fit(): This method supports incremental learning for large datasets. It’s particularly useful when you can’t fit the entire dataset into memory at once.

* Apply Feature Selection: Reducing the number of features in your dataset can significantly reduce memory usage and computation time.

* Leverage joblib for Parallel Processing: This library can be used to distribute tasks across multiple cores, which can greatly speed up your computations.

In [7]:
from sklearn.linear_model import SGDClassifier
import numpy as np

# Initialize a stochastic Gradient Descent (SGD) Classifier model
model = SGDClassifier()

# Loop through 10 batches of data
for batch in range(10):
    # Generate a batch of random data
    X_batch = np.random.rand(1000, 20)  # 1000 samples, 20 features
    y_batch = np.random.randint(0, 2, size=1000)  # Binary target variable containing either 0 or 1
    # use the partial_fit method to train the model on the current batch of data
    # the 'classes' parameter is specified to ensure the model is aware of the classes it's training on
    
    # Fit the model on the current batch
    model.partial_fit(X_batch, y_batch, classes=[0,1])

https://www.codecademy.com/article/scikit-learn-tutorial

In [8]:
import sklearn
print (sklearn.__version__)

1.7.0


In [13]:
from sklearn.datasets import load_iris

# load the data 
iris = load_iris()

# strre the feature matrix (X) and reponse vector (y)

X = iris.data 

y = iris.target # Target : species of iris

print("Feature names:", iris.feature_names)

print("Target names:", iris.target_names)

# Examine the first few rows of the data

print("\n First 5 rows of X:\n", X[:5])

Feature names: ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
Target names: ['setosa' 'versicolor' 'virginica']

 First 5 rows of X:
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


In [14]:
from sklearn.model_selection import train_test_split

# Split data into 70% training and 30% testing

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Check the shapes to confirm the split

print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)


X_train shape: (105, 4)
X_test shape: (45, 4)
y_train shape: (105,)
y_test shape: (45,)


In [15]:
from sklearn.neighbors import KNeighborsClassifier

# Create a KNN classifier with k=3

knn = KNeighborsClassifier(n_neighbors=3)

# Train the model using the training sets

knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=3)

In [17]:
# Predict the response for test dataset

y_pred = knn.predict(X_test)

# Display the first few predictions

print("First 5 predictions:", y_pred[:45])

print("First 5 true labels:", y_test[:45])

First 5 predictions: [1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0 0 0 1 0 0 2 1
 0 0 0 2 1 1 0 0]
First 5 true labels: [1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0 0 0 1 0 0 2 1
 0 0 0 2 1 1 0 0]


In [19]:
# Evaluate the model

from sklearn import metrics
# Check accuracy 

accuracy = metrics.accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy*100:.2f}%")

# generate a classification report
print("\nClassification Report:")

print(metrics.classification_report(y_test, y_pred, target_names=iris.target_names))

# Create a confusion matrix

print("\nConfusion Matrix:")

print(metrics.confusion_matrix(y_test, y_pred))

Accuracy: 100.00%

Classification Report:
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        19
  versicolor       1.00      1.00      1.00        13
   virginica       1.00      1.00      1.00        13

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45


Confusion Matrix:
[[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]


In [20]:
# Pipeline Integration

from sklearn.pipeline import Pipeline

from sklearn.preprocessing import StandardScaler

from sklearn.linear_model import LogisticRegression

pipe = Pipeline([
    ('scaler', StandardScaler() ),
    ('classifier', LogisticRegression() )
    
])

# Now you can use this pipeline like any other estimator

pipe.fit(X_train, y_train)

predictions = pipe.predict(X_test)

In [23]:
#Model Persistence

import joblib

# Save the model

joblib.dump(pipe, 'model.pkl')

# Load the model

loaded_model = joblib.load('model.pkl')